/**
 * Sunday Render Service
 * Sunday Render Service
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: molnar.balint@mdy.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package hu.sundayit.renderservice.client;

import hu.sundayit.renderservice.client.ApiException;
import hu.sundayit.renderservice.models.FileEntity;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FilerestApi
 */
public class FilerestApiTest {

    private final FilerestApi api = new FilerestApi();

    
    /**
     * Creates a file
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFileEntityUsingPOSTTest() throws ApiException {
        FileEntity fileToCreate = null;
        // FileEntity response = api.createFileEntityUsingPOST(fileToCreate);

        // TODO: test validations
    }
    
    /**
     * Gets a file eneity, its metadata read from the database and its contents read from the file storage
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFileEntityUsingGETTest() throws ApiException {
        Long id = null;
        // FileEntity response = api.getFileEntityUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * Gets all file entities by a project. Note, that this operation only queries the database, and not the file contents.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFilesByProjectIdUsingGETTest() throws ApiException {
        Long projectId = null;
        // List<FileEntity> response = api.getFilesByProjectIdUsingGET(projectId);

        // TODO: test validations
    }
    
    /**
     * Updates a file
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFileContentsUsingPOSTTest() throws ApiException {
        FileEntity fileToUpdate = null;
        // FileEntity response = api.updateFileContentsUsingPOST(fileToUpdate);

        // TODO: test validations
    }
    
}
