/**
 * Sunday Render Service
 * Sunday Render Service
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: molnar.balint@mdy.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package hu.sundayit.renderservice.client;

import hu.sundayit.renderservice.client.ApiException;
import hu.sundayit.renderservice.models.IterableProjectEntity;
import hu.sundayit.renderservice.models.ProjectEntity;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectrestApi
 */
public class ProjectrestApiTest {

    private final ProjectrestApi api = new ProjectrestApi();

    
    /**
     * Deletes a project, its document types, and its files.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProjectUsingDELETETest() throws ApiException {
        Long id = null;
        // api.deleteProjectUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * Returns all projects
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllProjectsUsingGETTest() throws ApiException {
        // IterableProjectEntity response = api.getAllProjectsUsingGET();

        // TODO: test validations
    }
    
    /**
     * Gets a project by its ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProjectByIdUsingGETTest() throws ApiException {
        Long id = null;
        // ProjectEntity response = api.getProjectByIdUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * Creates a new project. The ID does not need to be filled, as it is generated automatically
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insertProjectUsingPOSTTest() throws ApiException {
        ProjectEntity project = null;
        // ProjectEntity response = api.insertProjectUsingPOST(project);

        // TODO: test validations
    }
    
    /**
     * Updates a project.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateProjectUsingPOSTTest() throws ApiException {
        Long id = null;
        ProjectEntity project = null;
        // ProjectEntity response = api.updateProjectUsingPOST(id, project);

        // TODO: test validations
    }
    
}
