/**
 * Sunday Render Service
 * Sunday Render Service
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: molnar.balint@mdy.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package hu.sundayit.renderservice.client;

import hu.sundayit.renderservice.client.ApiException;
import hu.sundayit.renderservice.models.RenderRequestEntity;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RenderrequestrestApi
 */
public class RenderrequestrestApiTest {

    private final RenderrequestrestApi api = new RenderrequestrestApi();

    
    /**
     * Handles a render request and returns
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void renderRequestUsingPOSTTest() throws ApiException {
        RenderRequestEntity renderRequestEntity = null;
        // byte[] response = api.renderRequestUsingPOST(renderRequestEntity);

        // TODO: test validations
    }
    
}
